import { StyleSheet } from 'react-native';
import { APP_COLORS, APP_TYPO } from './appTheme';

export const appThemeStyles = StyleSheet.create({
  fullScreen: { flex: 1 },
  screenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.22)',
  },
  screenHeaderCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  screenHeaderTitle: {
    fontSize: APP_TYPO.screenTitle,
    fontWeight: '700',
    color: APP_COLORS.textPrimary,
    letterSpacing: -0.3,
    textAlign: 'center',
  },
  screenHeaderSubtitle: {
    fontSize: APP_TYPO.screenSubtitle,
    fontWeight: '600',
    color: APP_COLORS.textSoft,
    textAlign: 'center',
    marginTop: 2,
  },
  headerIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
  },
  sectionEyebrow: {
    fontSize: APP_TYPO.labelCaps,
    fontWeight: '800',
    color: APP_COLORS.accent,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
    gap: 16,
    paddingTop: 12,
  },
  card: {
    backgroundColor: APP_COLORS.surface,
    borderRadius: 20,
    padding: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: APP_COLORS.cardBorder,
    shadowColor: APP_COLORS.textPrimary,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  cardTitle: {
    fontSize: APP_TYPO.sectionTitle,
    fontWeight: '700',
    color: APP_COLORS.textSecondary,
    marginBottom: 12,
  },
  body: {
    fontSize: APP_TYPO.bodySmall,
    color: APP_COLORS.textMuted,
    lineHeight: 20,
  },
});
