import { StyleSheet } from 'react-native';
import { Category } from '../types';

export const CATEGORY_ICON: Record<Category, string> = {
  Accommodation: 'bed-outline',
  Dining: 'restaurant-outline',
  Transport: 'car-outline',
  Activities: 'ticket-outline',
  Shopping: 'bag-handle-outline',
  Emergency: 'medkit-outline',
  Other: 'ellipsis-horizontal-circle-outline',
};

export const CATEGORY_COLOR: Record<Category, string> = {
  Accommodation: '#8B5CF6',
  Dining: '#F59E0B',
  Transport: '#3B82F6',
  Activities: '#10B981',
  Shopping: '#EC4899',
  Emergency: '#EF4444',
  Other: '#64748B',
};

export const STATUS_COLOR = {
  onTrack: { bg: '#DCFCE7', text: '#166534', dot: '#22c55e' },
  warning: { bg: '#FFE4E6', text: '#BE123C', dot: '#FB7185' },
  over: { bg: '#FEE2E2', text: '#B91C1C', dot: '#EF4444' },
};

export const ledgerStyles = StyleSheet.create({
  fullScreen: { flex: 1 },
  scrollBody: { flex: 1, paddingHorizontal: 20, paddingTop: 20 },
  scrollContent: { paddingBottom: 140 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.22)',
  },
  headerTitleWrap: { flex: 1, marginHorizontal: 12 },
  headerTitle: { fontSize: 15, fontWeight: '800', letterSpacing: 0.6, color: '#1f2937', textAlign: 'center' },
  headerSubtitle: { fontSize: 11, color: 'rgba(31,41,55,0.7)', textAlign: 'center', marginTop: 2 },
  headerSideSpacer: { width: 40, height: 40 },
  iconCircle: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.3)', alignItems: 'center', justifyContent: 'center' },
  pressedGlass: { backgroundColor: 'rgba(24, 58, 96, 0.42)', borderColor: 'rgba(255,255,255,0.5)' },
  smallAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.24)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
  },
  smallActionText: { color: '#0f172a', fontSize: 11, fontWeight: '800' },
  dashHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  tripName: { fontSize: 26, fontWeight: '900', color: '#0f172a', letterSpacing: -0.6 },
  tripMeta: { fontSize: 12, color: 'rgba(15,23,42,0.65)', marginTop: 4, fontWeight: '600' },
  card: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E1EAF9',
    borderWidth: 1,
    borderRadius: 22,
    padding: 18,
    marginTop: 16,
  },
  cardDark: {
    backgroundColor: '#FFE4E6',
    borderColor: '#FDA4AF',
    borderWidth: 1,
    borderRadius: 22,
    padding: 18,
    marginTop: 16,
  },
  cardLabel: { fontSize: 11, fontWeight: '800', color: 'rgba(15,23,42,0.6)', textTransform: 'uppercase', letterSpacing: 1 },
  cardLabelLight: { fontSize: 11, fontWeight: '800', color: '#9F1239', textTransform: 'uppercase', letterSpacing: 1 },
  bigAmount: { fontSize: 22, fontWeight: '900', color: '#0f172a', marginTop: 6 },
  bigAmountLight: { fontSize: 22, fontWeight: '900', color: '#0f172a', marginTop: 6 },
  amountSub: { fontSize: 12, color: 'rgba(15,23,42,0.6)', fontWeight: '600' },
  amountSubLight: { fontSize: 12, color: 'rgba(15,23,42,0.6)', fontWeight: '600' },
  progressTrack: { height: 10, borderRadius: 999, backgroundColor: '#E7EEFC', overflow: 'hidden', marginTop: 12 },
  progressTrackLight: { height: 10, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.22)', overflow: 'hidden', marginTop: 12 },
  progressFill: { height: '100%', borderRadius: 999 },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statPill: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, flexDirection: 'row', alignItems: 'center', gap: 5 },
  statPillDot: { width: 6, height: 6, borderRadius: 3 },
  statPillText: { fontSize: 10, fontWeight: '800' },
  sectionTitle: { fontSize: 13, fontWeight: '800', color: '#0f172a', marginTop: 22, marginBottom: 4, textTransform: 'uppercase', letterSpacing: 0.8 },
  insightBox: { flexDirection: 'row', gap: 10, backgroundColor: '#EFF6FF', borderColor: '#DBEAFE', borderWidth: 1, borderRadius: 16, padding: 12, marginTop: 12 },
  insightText: { flex: 1, fontSize: 12, color: '#1e3a8a', lineHeight: 18, fontWeight: '600' },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderColor: '#E1EAF9',
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    marginTop: 10,
  },
  dateRowLabel: { fontSize: 14, fontWeight: '800', color: '#0f172a' },
  dateRowSub: { fontSize: 11, color: 'rgba(15,23,42,0.6)', marginTop: 3, fontWeight: '600' },
  expenseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E1EAF9',
    borderWidth: 1,
    borderRadius: 16,
    padding: 12,
    marginTop: 10,
    gap: 12,
  },
  categoryIconWrap: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  expenseName: { fontSize: 13, fontWeight: '800', color: '#0f172a' },
  expenseSub: { fontSize: 11, color: 'rgba(15,23,42,0.6)', marginTop: 2, fontWeight: '600' },
  expenseAmount: { fontSize: 14, fontWeight: '900', color: '#0f172a' },
  primaryButton: { width: '100%', minHeight: 48, borderRadius: 16, justifyContent: 'center', alignItems: 'center', paddingVertical: 12, marginTop: 20 },
  primaryButtonText: { fontSize: 15, fontWeight: '800', color: '#fff' },
  secondaryButton: { width: '100%', minHeight: 44, borderRadius: 16, justifyContent: 'center', alignItems: 'center', paddingVertical: 10, marginTop: 10, borderWidth: 1, borderColor: '#E1EAF9', backgroundColor: '#FFFFFF' },
  secondaryButtonText: { fontSize: 13, fontWeight: '800', color: '#0f172a' },
  label: { fontSize: 11, fontWeight: '700', color: 'rgba(15,23,42,0.65)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 6, marginTop: 14 },
  input: { backgroundColor: '#FFFFFF', borderColor: '#E1EAF9', borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, color: '#0f172a', fontSize: 14, fontWeight: '600' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 6 },
  chip: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, borderWidth: 1 },
  chipSelected: { backgroundColor: '#2563EB', borderColor: '#1D4ED8' },
  chipUnselected: { backgroundColor: '#FFFFFF', borderColor: '#E1EAF9' },
  chipText: { fontSize: 12, fontWeight: '700' },
  travelerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FFFFFF', borderRadius: 14, borderWidth: 1, borderColor: '#E1EAF9', paddingHorizontal: 14, paddingVertical: 10, marginTop: 8 },
  travelerName: { fontSize: 13, fontWeight: '700', color: '#0f172a' },
  stepperRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 18, marginTop: 10 },
  stepperButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(37,99,235,0.14)', alignItems: 'center', justifyContent: 'center' },
  stepperValue: { fontSize: 22, fontWeight: '900', color: '#0f172a', minWidth: 32, textAlign: 'center' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: '#eef4fb', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 20, maxHeight: '82%' },
  modalTitle: { fontSize: 16, fontWeight: '900', color: '#0f172a' },
  itemRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#E1EAF9', padding: 12, marginTop: 10, gap: 10 },
  scanArea: { height: 190, borderRadius: 24, borderWidth: 2, borderColor: 'rgba(255,255,255,0.5)', borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.1)', marginTop: 16 },
  strategyCard: { borderRadius: 18, borderWidth: 2, padding: 14, marginTop: 10 },
  bottomBar: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 20, paddingBottom: 24, paddingTop: 12, backgroundColor: 'rgba(255,255,255,0.4)', borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.5)' },
  inputRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  calendarButton: { width: 44, height: 44, borderRadius: 12, backgroundColor: 'rgba(15,23,42,0.08)', borderWidth: 1, borderColor: 'rgba(15,23,42,0.15)', alignItems: 'center', justifyContent: 'center' },
  calendarHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 4 },
  calendarNavButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: 'rgba(37,99,235,0.12)', alignItems: 'center', justifyContent: 'center' },
  calendarMonthLabel: { fontSize: 14, fontWeight: '800', color: '#0f172a' },
  calendarWeekRow: { flexDirection: 'row', marginTop: 14 },
  calendarWeekDayCell: { flex: 1, alignItems: 'center' },
  calendarWeekDayText: { fontSize: 10, fontWeight: '800', color: 'rgba(15,23,42,0.5)', textTransform: 'uppercase' },
  calendarDayRow: { flexDirection: 'row', marginTop: 6 },
  calendarDayCell: { flex: 1, aspectRatio: 1, alignItems: 'center', justifyContent: 'center' },
  calendarDayCircle: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  calendarDayText: { fontSize: 12, fontWeight: '700', color: '#0f172a' },
  calendarDaySelected: { backgroundColor: '#2563eb' },
  calendarDayTextSelected: { color: '#fff', fontWeight: '900' },
  calendarDayToday: { borderWidth: 1, borderColor: '#2563eb' },
});
